In [1]:
import numpy                                                   

In [2]:
import numpy as np

In [3]:
np.__version__

'1.21.5'

In [4]:
np.array([2,4,6,8,10])

array([ 2,  4,  6,  8, 10])

In [5]:
np.array([2,4,6,8,10], dtype='float32')

array([ 2.,  4.,  6.,  8., 10.], dtype=float32)

In [6]:
np.zeros(10,dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3,4),dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [8]:
np.full((3,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [12]:
np.random.random((4,4))

array([[0.80303704, 0.77061483, 0.93887935, 0.83342017],
       [0.55967133, 0.36811687, 0.86847366, 0.92703364],
       [0.84845756, 0.9993525 , 0.34343508, 0.93921201],
       [0.35480994, 0.89464183, 0.61144534, 0.17632238]])

In [13]:
np.random.normal(0,1,(3,3))

array([[-2.19013971,  0.17077568,  0.40874144],
       [ 2.12334425,  0.87550211, -0.28090359],
       [ 1.2248945 ,  0.22649981, -1.05916581]])

In [14]:
np.random.randint(0,10,(3,3))

array([[6, 9, 3],
       [3, 8, 9],
       [1, 1, 7]])

In [15]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
np.empty(3)

array([0.33333333, 0.66666667, 1.        ])

In [22]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)

In [38]:
x1

array([5, 0, 3, 3, 7, 9])

In [39]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x2 = np.random.randint(10, size=(3,4))

In [25]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [26]:
x3 = np.random.randint(10, size=(3,4,5))

In [27]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [29]:
print('x3 ndim:',x3.ndim)

x3 ndim: 3


In [30]:
print('x3 shape:',x3.shape)

x3 shape: (3, 4, 5)


In [31]:
print('x3 size:',x3.size)

x3 size: 60


In [32]:
print('x3 dtype:',x3.dtype)

x3 dtype: int32


In [35]:
print('x3 itemsize:',x3.itemsize,'bytes')

x3 itemsize: 4 bytes


In [37]:
print('x3 nbytes:',x3.nbytes)

x3 nbytes: 240


In [40]:
x1[1]

0

In [41]:
x1[-1]

9

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
x2[0,0]

3

In [44]:
x2[2,-1]

7

In [45]:
x2[0,0]=9

In [46]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [47]:
x1

array([5, 0, 3, 3, 7, 9])

In [48]:
x1[0]=1.32

In [49]:
x1

array([1, 0, 3, 3, 7, 9])

In [50]:
x = np.arange(10)

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x[:5]

array([0, 1, 2, 3, 4])

In [53]:
x[-1]

9

In [54]:
x[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[::2]

array([0, 2, 4, 6, 8])

In [56]:
x[2::2]

array([2, 4, 6, 8])

In [57]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [58]:
x[5::-2]

array([5, 3, 1])

In [59]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [60]:
x2[:2, :3]

array([[9, 5, 2],
       [7, 6, 8]])

In [62]:
x2[:,:3]

array([[9, 5, 2],
       [7, 6, 8],
       [1, 6, 7]])

In [63]:
x2[:,::2]

array([[9, 2],
       [7, 8],
       [1, 7]])

In [64]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [66]:
print(x2[0,:])

[9 5 2 4]


In [67]:
x2[0]

array([9, 5, 2, 4])

In [68]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [69]:
print(x2)

[[9 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [70]:
x2_sub = x2[:2,:2]

In [71]:
print(x2_sub)

[[9 5]
 [7 6]]


In [72]:
x2_sub[0,0] = 88
print(x2_sub)

[[88  5]
 [ 7  6]]


In [73]:
x2_sub

array([[88,  5],
       [ 7,  6]])

In [74]:
x2

array([[88,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [75]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[88,  5],
       [ 7,  6]])

In [76]:
x2

array([[88,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [79]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [81]:
x.reshape((1,3))

array([[1, 2, 3]])

In [84]:
x.reshape(1,3)

array([[1, 2, 3]])

In [85]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [86]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [87]:
z = [11,12,23]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 11, 12, 23])

In [93]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [94]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [95]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [97]:
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [99]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)

[1 2 3] [99 99  3] [2 1]


In [103]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
upper, lower = np.vsplit(grid,[3])

In [108]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
lower

array([[12, 13, 14, 15]])

In [110]:
left, right = np.hsplit(grid,[2])

In [111]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [112]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [115]:
arr = np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
